#!/bin/bash
REMOTEHOST=($(ls -l *.key | awk '{ print $9 }'  | sed 's/\(.\+\)\.key/\1/g'))
REMOTEPORT=10050
TIMEOUT=1
for i in "${REMOTEHOST[@]}"; do
        if  nc -w $TIMEOUT -z $i $REMOTEPORT ; then
        echo "I was able to connect to ${i}"
        echo $i >> up.txt
        else
        echo "Connection to ${i} failed."
        echo $i >> down.txt
        fi
done
