#!/bin/bash
REMOTEHOST=($(ls -l1v *.key | awk '{ print $9 }'  | sed 's/[ -]\+/-/g'| sed 's/\(.\+\)\.key/\1/g'))
REMOTEPORT=10050
TIMEOUT=1
for i in "${REMOTEHOST[@]}"; do
        if  nc -w $TIMEOUT -z $i $REMOTEPORT ; then
        echo "I was able to connect to ${i}"
        
        j=($(getent hosts $i | awk '{ print $1 }'))
        echo $i" | "$j | tr [a-z] [A-Z] >> up.txt
        else
        echo "Connection to ${i} failed."
        echo $i >> down.txt
        fi
done
sed -e 's/^./\U&/' up.txt > vpn-R.txt
